### ISSUE TITLE
Additional maintainers?

### ISSUE THREAD

**Issue by kibertoad** [JUtupe/ktor-rabbitmq#1]
Hi! We are considering using RabbitMQ together with ktor, and considering that this library is not very actively developed, would like to chime in with some additional development effort. Ideally we would prefer to stay upstream rather than just fork it. Would you be open to accept additional developers into the project?

**Comment by JUtupe** [comment]
Hello! I'm happy to hear that someone wants to help with this ktor library. Feel free to open an issue or submit a pull request. I'll add you as a collaborator. 

It's worth noting that ktor is in process of developing version 2.0 in which they change custom feature development. It may not be worth working on this one before the next major version is released. 

Regards, Wiktor :)

**Comment by kibertoad** [comment]
Thank you! I'll start by creating some issues, if you don't mind, then we can plan further steps :)

**Comment by kibertoad** [comment]
On topic of 2.0 release -> I doubt it's going to cause significant code waste, most likely same code would need to be rearranged somewhat, so that's a risk I'm willing to take at this point.
