### ISSUE TITLE
Gradle repo configuration

### ISSUE THREAD

**Issue by kibertoad** [JUtupe/ktor-rabbitmq#14]
Looks like ktor-rabbitmq is not available on Maven Central: https://mvnrepository.com/search?q=ktor-rabbitmq

Which repo needs to be added to be able to install ktor-rabbitmq?

btw, should it be `pl.jutupe` or `com.github.JUtupe`? Code and documentation seem inconsistent in this regard.

**Comment by JUtupe** [comment]
https://jitpack.io/#JUtupe/ktor-rabbitmq

Currently it is published on jitpack, I'll try to publish it on maven in future.

**Comment by kibertoad** [comment]
Can you add necessary gradle config to the readme? most people use maven central by default.

**Comment by JUtupe** [comment]
I'll work on it in #6

**Comment by JUtupe** [comment]
I've added gradle config here: https://github.com/JUtupe/ktor-rabbitmq/wiki

I'm closing this issue for now
