### ISSUE TITLE
Help using RabbitMQInstance

### ISSUE THREAD

**Issue by ArnauKokoro** [JUtupe/ktor-rabbitmq#23]
Hi @JUtupe @kibertoad,

I'm trying to externalize the instance created inside the install(), but I can't get the instance outside the install() works. It throws an error ("late int uri not initialized") because it tries to initialize the instance before finalize the install() instead of wait to initialize() manually.

```
var rabbitMQInstance: RabbitMQInstance?
install(RabbitMQ) {
    rabbitMQInstance = RabbitMQInstance(RabbitMQConfiguration.create()
        .apply {
            uri = "amqp://guest:guest@${rabbit.host}:${rabbit.amqpPort}"
            connectionName = "Connection name"

            serialize { jacksonObjectMapper().writeValueAsBytes(it) }
            deserialize { bytes, type -> jacksonObjectMapper().readValue(bytes, type.javaObjectType) }

            initialize {
                // ...
            }
        })
}
```

If I don't set that _var rabbitMQInstance: RabbitMQInstance?_ it works and it initialize that instance before finalize the install, but I can't use that rabbitMQInstance anywhere because it's inside the install().

How can I get that instance outside the install()?

Many thanks!!

**Comment by ArnauKokoro** [comment]
Finally, I got it working. I'm creating a RabbitMQInstance before the install(). When I want to initialize the service, I do make the install() passing by rabbitMQInstance = MyRabbitMQInstance and the install() initialize the service.

```
val MyRabbitMQInstance = RabbitMQInstance(RabbitMQConfiguration.create()
        .apply {
            uri = "amqp://guest:guest@${rabbit.host}:${rabbit.amqpPort}"
            connectionName = "Connection name"

            serialize { jacksonObjectMapper().writeValueAsBytes(it) }
            deserialize { bytes, type -> jacksonObjectMapper().readValue(bytes, type.javaObjectType) }

            initialize {
                // ...
            }
        })

install(RabbitMQ) {
     rabbitMQInstance = MyRabbitMQInstance
}
```

So I can use that MyRabbitMQInstance as an application variable.

Thanks!!

**Comment by JUtupe** [comment]
Hi! I'm glad that you figured it out by yourself!

Thanks for using ktor-rabbitmq and sorry for not having enough time to respond earlier!

**Comment by ArnauKokoro** [comment]
Thanks @JUtupe !!

My problem was that I didn't understand that I could pass through parameter the already created instance from outside.
Because the same way I could pass the params for the config I could pass the rabbitMQInstance already created.

To figured out I did inspect what's in the RabbitMQ class which works as a ktor feature main class.
