### ISSUE TITLE
Feature not plugin

### ISSUE THREAD

**Issue by abdallahaymaan** [JUtupe/ktor-rabbitmq#30]
When I try 
   `install(RabbitMQ){
}`

It gives this error regarding that RabbitMQ is a feature not a plugin and the install function takes a plugin. I'm using Ktor 2.0.0.

Here is the exact error message ->
`Type mismatch.
Required: Plugin<TypeVariable(P), TypeVariable(B), TypeVariable(F)>
Found: RabbitMQ.Feature `

I would be really thankful if anyone could help with this!

**Comment by JUtupe** [comment]
Hi, thanks for filling an issue.

I forgot to release a new version after implementing ktor 2.0.0. The new version to fix this issue should be available here:

https://jitpack.io/#JUtupe/ktor-rabbitmq/v0.4.0

Feel free to close this issue if it solves your error :)

**Comment by abdallahaymaan** [comment]
Thanks alot!
