### ISSUE TITLE
Support for work queues

### ISSUE THREAD

**Issue by kibertoad** [JUtupe/ktor-rabbitmq#4]
Is it possible to consume work queues (https://www.rabbitmq.com/tutorials/tutorial-two-java.html) using current implementation, or it only works with message exchanges and ktor-rabbitmq would need to be extended for that?

**Comment by kibertoad** [comment]
@JUtupe Can you comment on this one?

**Comment by JUtupe** [comment]
As far as i know ktor-rabbitmq would need to be extended to support work queues

**Comment by kibertoad** [comment]
I'll look into this.
