### ISSUE TITLE
Ktor 3 & Kotlin 2 support

### ISSUE THREAD

**Issue by Laxystem** [JUtupe/ktor-rabbitmq#46]
Is this repository maintained?

If so - can you please update to support Ktor 3 and Kotlin 2?

**Comment by JUtupe** [comment]
Hey @Laxystem, there's a new version of the library out. I switched to using GitHub Packages instead of JitPack. Can you give it a try and see if it works? https://github.com/JUtupe/ktor-rabbitmq/packages/2336516

**Comment by Laxystem** [comment]
Can't, I ended up using the Java library itself - it works, I don't see a reason to setup Ktor server.
